In this notebook, we will prepare the shell scripts to train and test the predictive model.

In [1]:
import pandas as pd
import random
import numpy as np

seed=99
random.seed(seed)
np.random.seed(seed)

In [2]:
rental = pd.read_csv('../data/rental.csv')

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(rental, test_size=0.2)

X_train.head()

,instant,temp,atemp,hum,windspeed,cnt,season_1,season_2,season_3,season_4,...,weekday_3,weekday_4,weekday_5,weekday_6,workingday_0,workingday_1,weathersit_1,weathersit_2,weathersit_3,weathersit_4
11631,11632,0.68,0.6364,0.51,0.1045,313,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
7488,7489,0.50,0.4848,0.42,0.3284,310,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
11785,11786,0.42,0.4242,0.50,0.2537,135,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
9048,9049,0.46,0.4545,0.72,0.3881,90,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
15605,15606,0.46,0.4545,0.67,0.0000,228,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [7]:
X_train.to_csv('../data/train.csv', index=False)
X_test.to_csv('../data/test.csv', index=False)